apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: gnu-hc-cert
  namespace: gnu-hc
spec:
  secretName: gnu-hc-tls
  subject:
    organizations:
      - OpenDX
  dnsNames:
    - "gnu-hc.193.147.109.10.nip.io"
  issuerRef:
    name: buypass-issuer
    kind: ClusterIssuer
